### PR TITLE
Add NSCameraUsageDescription to Forms’ Simple Sample

### PR DESCRIPTION
**Pull request by lucatorella**

### CODE REVIEW

**Comment by lucatorella** [comment]
where is the cherry-pick button? 🤔

**Comment by petradonka** [comment]
huhh no clue, @TomekJurkowski you just did this for RN, right? 😄

**Comment by TomekJurkowski** [comment]
I don't have good news for you, there was never a cherrypick button in github as far as I remember 🤷‍♂️  You need to go deeper and prepare the cherrypicks yourself - retro style -  from the command line or some git clients, if you prefer those (I can help you with command line if you want).

**Comment by lucatorella** [comment]
don't worry I remember how to do it manually 😉 I just somehow remembered a cherry-pick button in github 🤔

**Comment by petradonka** [comment]
I could've sworn there's one too, I guess we were wrong 😄 "spoiled" by GitLab

**Pull request merged**
